#!/usr/bin/env ruby

require_relative 'bootstrap_ar'
database = ENV['FP_ENV'] || 'development'
connect_to database

# ARGV = add foo
command = ARGV[0]
trip_name = ARGV[1]

params = { command: command, trip: { name: trip_name } }
controller = TripController.new(params)
# routes = { "add" => :create, "list" => :index, "delete" => :destroy }

# Look into finishing
# if route = routes[command]
#   controller.send route
# else
#   unless command == "help"

if command == "add"
  controller.create
elsif command == "list"
  controller.index
elsif command == "delete"
  controller.destroy
end