#!/usr/bin/env ruby

require_relative 'bootstrap_ar'

# ARGV = add foo
command = ARGV[0]

if command == "add"
  trip_name = ARGV[1]
  trip = Trip.create( name: trip_name )
  if trip.save
    puts "Successfully added new trip #{trip_name}."
  else
    puts "Failed: #{trip.errors.full_messages.join(", ")}."
  end
elsif command == "list"
  trips = Trip.all
  trips.each_with_index do |trip, i|
   puts "#{i+1}. #{trip.name}"
  end
end