#!/usr/bin/env ruby

require_relative 'bootstrap_ar'
database = ENV['FP_ENV'] || 'development'
connect_to database

# ARGV = add foo
command = ARGV[0]
trip_name = ARGV[1]
category_name = ARGV[2]
amount = ARGV[3]

params = { command: command, trip: { name: trip_name }, category: { name: category_name }, amount: { integer: amount } }

controller = TripController.new(params)

# routes = { "add" => :create, "list" => :index, "remove" => :destroy }

# Look into finishing
# if route = routes[command]
#   controller.send route
# else
#   unless command == "help"

if command == "add"
  controller.create
elsif command == "list"
  controller.index
elsif command == "remove"
  controller.destroy
elsif command == "cat"
  controller = CategoryController.new
  controller.index
elsif command == "set"
  controller.set_category_budget
elsif command == "balance"
  controller = ExpenseController.new(params)
  controller.get_balance
elsif command == "expense"
  controller = ExpenseController.new(params)
  if trip_name == 'list'
    controller.index
  else
    controller.create
  end
end